name: "Build and publish docker container"
description: "Builds the project and the docker container and publishes it to docker hub"
runs:
  using: "composite"
  steps:
    - name: Checkout source and setup Java
      uses: dasch-swiss/shacl-cli/.github/actions/preparation@main
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish docker image to Dockerhub
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        export DOCKER_BUILDKIT=1; ./sbtx "root / Docker / publish"
