name: "Build and publish docker container"
description: "Builds the project and the docker container and publishes it to docker hub"
inputs:
  docker-hub-token:
    description: "Docker Hub token"
    required: true
  docker-user:
    description: "Docker Hub username"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source and setup Java
      uses: dasch-swiss/shacl-cli/.github/actions/preparation@main
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and publish docker image to Dockerhub
      shell: bash
      run: |
        echo ${{ inputs.docker-hub-token }} | docker login -u ${{ inputs.docker-user }} --password-stdin
        export DOCKER_BUILDKIT=1; ./sbtx "root / Docker / publish"
