# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source and setup Java
        uses: dasch-swiss/shacl-cli/.github/actions/preparation@main
      - name: Run tests
        run: ./sbtx test

  docker-it:
    name: Docker integration test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout source and setup Java
        uses: dasch-swiss/shacl-cli/.github/actions/preparation@main
      - name: Build docker image locally
        run: ./sbtx "root/Docker/publishLocal"
      - name: Run docker integration test
        run: bash scripts/it/docker-it.sh
