name: Release-create-release

on:
  pull_request:
    types:
      - closed

jobs:
  create-release:
    name: Create release PR
    runs-on: ubuntu-latest
    # Automate releases with Conventional Commit Messages as Pull Requests are merged into "main" branch
    if: github.event.pull_request.merged == true
    steps:
      - name: Run release please action
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          draft-pull-request: true
          release-type: simple
          package-name: dsp-api
          pull-request-title-pattern: "chore${scope}: Release${component} ${version}"
          changelog-types: '[
              {"type": "build", "section": "Maintenances"},
              {"type": "chore", "section": "Maintenances"},
              {"type": "docs", "section": "Documentation"},
              {"type": "feat", "section": "Enhancements"},
              {"type": "fix", "section": "Bug Fixes"},
              {"type": "perf", "section": "Performance Improvements"},
              {"type": "refactor", "section": "Maintenances"},
              {"type": "test", "section": "Tests"},
              {"type": "deprecated", "section": "Deprecated"}
            ]'
