name: Docker publish Webapi and Sipi images

on:
  push:
    branches:
      - main

jobs:
  publish-from-branch:
    if: github.event_name != 'release'
    name: Publish
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.output_docker_image_tag.outputs.tag }}
    steps:
      - name: Checkout source and setup Java
        uses: dasch-swiss/shacl-cli/.github/actions/preparation@main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and publish docker image to Dockerhub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          export DOCKER_BUILDKIT=1; ./sbtx "root / Docker / publish"
      - name: Output docker image tag
        id: output_docker_image_tag
        run: echo "tag=$(make docker-image-tag | tr -d '\n')" >> "$GITHUB_OUTPUT"
        shell: bash # Explicit for fail-fast behaviour
